name: Test runner job

on:
  workflow_dispatch:
  
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Build project with Maven and run test
      run: mvn -B package --file pom.xml
    - name: Run tests
      run: mvn -B clean test
      
  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
         authToken: ${{secrets.GITHUB_TOKEN}}
         context: 'Test report'
         state: 'success'
         sha: ${{ github.event.pull_request.head.sha }}
         target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
